apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authinject.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "authinject.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "authinject.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: SPICEDB_ENDPOINT
              value: {{ .Values.env.SPICEDB_ENDPOINT | quote }}
            - name: QDRANT_URL
              value: {{ .Values.env.QDRANT_URL | quote }}
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
